# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bf032e790d64d2876515e2ff368f7178d401c64d8324016ad45b872dfd0837b967efb5f8f5e014b5dc8d3a59235f02d68778c05ee9bc23e6a671f131b32d9fe

test:
  secret_key_base: 2829be85d687ea4e6f312a72cac14562cbd70f161ce1db13bf73a8bd8b2d53110962b7dda33bcaaf369b89f5d9940161dbbc277e439bd4dee0408abc061a167c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
